# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS TMIV::libmd5 TMIV::TLibCommon TMIV::TLibDecoder TMIV::vvencFFapp TMIV::vvdecapp TMIV::CommonLib TMIV::fmt TMIV::MivBitstreamLib TMIV::IOLib TMIV::ViewOptimizerLib TMIV::PrunerLib TMIV::AggregatorLib TMIV::PackerLib TMIV::GeometryQuantizerLib TMIV::RendererLib TMIV::RendererFrontLib TMIV::Renderer TMIV::ViewingSpaceLib TMIV::VideoDecoderLib TMIV::EncoderLib TMIV::Encoder TMIV::MpiEncoder TMIV::Multiplexer TMIV::DecoderLib TMIV::Decoder TMIV::Parser TMIV::BitrateReport TMIV::DepthQualityAssessorLib)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target TMIV::libmd5
add_library(TMIV::libmd5 STATIC IMPORTED)

set_target_properties(TMIV::libmd5 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Workspace/tmiv_build/_deps/hm-src//source/Lib"
)

# Create imported target TMIV::TLibCommon
add_library(TMIV::TLibCommon STATIC IMPORTED)

set_target_properties(TMIV::TLibCommon PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CXX_COMPILER_ID:MSVC>:_CRT_SECURE_NO_WARNINGS>"
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:Clang>:-w>;\$<\$<CXX_COMPILER_ID:GNU>:-w>"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Workspace/tmiv_build/_deps/hm-src//source/Lib"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:TMIV::libmd5>"
)

# Create imported target TMIV::TLibDecoder
add_library(TMIV::TLibDecoder STATIC IMPORTED)

set_target_properties(TMIV::TLibDecoder PROPERTIES
  INTERFACE_LINK_LIBRARIES "TMIV::TLibCommon"
)

# Create imported target TMIV::vvencFFapp
add_executable(TMIV::vvencFFapp IMPORTED)

# Create imported target TMIV::vvdecapp
add_executable(TMIV::vvdecapp IMPORTED)

# Create imported target TMIV::CommonLib
add_library(TMIV::CommonLib STATIC IMPORTED)

set_target_properties(TMIV::CommonLib PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Common/include"
  INTERFACE_LINK_LIBRARIES "TMIV::fmt"
)

# Create imported target TMIV::fmt
add_library(TMIV::fmt STATIC IMPORTED)

set_target_properties(TMIV::fmt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "FMT_LOCALE"
  INTERFACE_COMPILE_FEATURES "cxx_variadic_templates"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Workspace/tmiv_build/_deps/fmt-src/include"
)

# Create imported target TMIV::MivBitstreamLib
add_library(TMIV::MivBitstreamLib STATIC IMPORTED)

set_target_properties(TMIV::MivBitstreamLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/MivBitstream/include"
  INTERFACE_LINK_LIBRARIES "TMIV::CommonLib"
)

# Create imported target TMIV::IOLib
add_library(TMIV::IOLib STATIC IMPORTED)

set_target_properties(TMIV::IOLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/IO/include"
  INTERFACE_LINK_LIBRARIES "TMIV::MivBitstreamLib"
)

# Create imported target TMIV::ViewOptimizerLib
add_library(TMIV::ViewOptimizerLib STATIC IMPORTED)

set_target_properties(TMIV::ViewOptimizerLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/ViewOptimizer/include"
  INTERFACE_LINK_LIBRARIES "TMIV::RendererLib"
)

# Create imported target TMIV::PrunerLib
add_library(TMIV::PrunerLib STATIC IMPORTED)

set_target_properties(TMIV::PrunerLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Pruner/include"
  INTERFACE_LINK_LIBRARIES "TMIV::RendererLib"
)

# Create imported target TMIV::AggregatorLib
add_library(TMIV::AggregatorLib STATIC IMPORTED)

set_target_properties(TMIV::AggregatorLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Aggregator/include"
  INTERFACE_LINK_LIBRARIES "TMIV::CommonLib"
)

# Create imported target TMIV::PackerLib
add_library(TMIV::PackerLib STATIC IMPORTED)

set_target_properties(TMIV::PackerLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Packer/include"
  INTERFACE_LINK_LIBRARIES "TMIV::MivBitstreamLib"
)

# Create imported target TMIV::GeometryQuantizerLib
add_library(TMIV::GeometryQuantizerLib STATIC IMPORTED)

set_target_properties(TMIV::GeometryQuantizerLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/GeometryQuantizer/include"
  INTERFACE_LINK_LIBRARIES "TMIV::MivBitstreamLib"
)

# Create imported target TMIV::RendererLib
add_library(TMIV::RendererLib STATIC IMPORTED)

set_target_properties(TMIV::RendererLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Renderer/include"
  INTERFACE_LINK_LIBRARIES "TMIV::ViewingSpaceLib;\$<LINK_ONLY:Threads::Threads>"
)

# Create imported target TMIV::RendererFrontLib
add_library(TMIV::RendererFrontLib STATIC IMPORTED)

set_target_properties(TMIV::RendererFrontLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Renderer/include"
  INTERFACE_LINK_LIBRARIES "TMIV::RendererLib;TMIV::IOLib"
)

# Create imported target TMIV::Renderer
add_executable(TMIV::Renderer IMPORTED)

# Create imported target TMIV::ViewingSpaceLib
add_library(TMIV::ViewingSpaceLib STATIC IMPORTED)

set_target_properties(TMIV::ViewingSpaceLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/ViewingSpace/include"
  INTERFACE_LINK_LIBRARIES "TMIV::MivBitstreamLib"
)

# Create imported target TMIV::VideoDecoderLib
add_library(TMIV::VideoDecoderLib STATIC IMPORTED)

set_target_properties(TMIV::VideoDecoderLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/VideoDecoder/include"
  INTERFACE_LINK_LIBRARIES "TMIV::MivBitstreamLib;\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:TMIV::TLibDecoder>"
)

# Create imported target TMIV::EncoderLib
add_library(TMIV::EncoderLib STATIC IMPORTED)

set_target_properties(TMIV::EncoderLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Encoder/include"
  INTERFACE_LINK_LIBRARIES "TMIV::ViewOptimizerLib;TMIV::PrunerLib;TMIV::AggregatorLib;TMIV::PackerLib;TMIV::GeometryQuantizerLib;TMIV::DepthQualityAssessorLib"
)

# Create imported target TMIV::Encoder
add_executable(TMIV::Encoder IMPORTED)

# Create imported target TMIV::MpiEncoder
add_executable(TMIV::MpiEncoder IMPORTED)

# Create imported target TMIV::Multiplexer
add_executable(TMIV::Multiplexer IMPORTED)

# Create imported target TMIV::DecoderLib
add_library(TMIV::DecoderLib STATIC IMPORTED)

set_target_properties(TMIV::DecoderLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/Decoder/include"
  INTERFACE_LINK_LIBRARIES "TMIV::VideoDecoderLib"
)

# Create imported target TMIV::Decoder
add_executable(TMIV::Decoder IMPORTED)

# Create imported target TMIV::Parser
add_executable(TMIV::Parser IMPORTED)

# Create imported target TMIV::BitrateReport
add_executable(TMIV::BitrateReport IMPORTED)

# Create imported target TMIV::DepthQualityAssessorLib
add_library(TMIV::DepthQualityAssessorLib STATIC IMPORTED)

set_target_properties(TMIV::DepthQualityAssessorLib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Workspace/tmiv/source/DepthQualityAssessor/include"
  INTERFACE_LINK_LIBRARIES "TMIV::RendererLib"
)

# Import target "TMIV::libmd5" for configuration "Debug"
set_property(TARGET TMIV::libmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::libmd5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/Debug/libmd5.lib"
  )

# Import target "TMIV::TLibCommon" for configuration "Debug"
set_property(TARGET TMIV::TLibCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::TLibCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/Debug/TLibCommon.lib"
  )

# Import target "TMIV::TLibDecoder" for configuration "Debug"
set_property(TARGET TMIV::TLibDecoder APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::TLibDecoder PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/Debug/TLibDecoder.lib"
  )

# Import target "TMIV::vvencFFapp" for configuration "Debug"
set_property(TARGET TMIV::vvencFFapp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::vvencFFapp PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/_deps/vvenc-build/source/App/vvencFFapp/Debug/vvencFFapp.exe"
  )

# Import target "TMIV::vvdecapp" for configuration "Debug"
set_property(TARGET TMIV::vvdecapp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::vvdecapp PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/_deps/vvdec-build/source/App/vvdecapp/Debug/vvdecapp.exe"
  )

# Import target "TMIV::CommonLib" for configuration "Debug"
set_property(TARGET TMIV::CommonLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::CommonLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Common/Debug/CommonLib.lib"
  )

# Import target "TMIV::fmt" for configuration "Debug"
set_property(TARGET TMIV::fmt APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::fmt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/_deps/fmt-build/Debug/fmtd.lib"
  )

# Import target "TMIV::MivBitstreamLib" for configuration "Debug"
set_property(TARGET TMIV::MivBitstreamLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::MivBitstreamLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/MivBitstream/Debug/MivBitstreamLib.lib"
  )

# Import target "TMIV::IOLib" for configuration "Debug"
set_property(TARGET TMIV::IOLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::IOLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/IO/Debug/IOLib.lib"
  )

# Import target "TMIV::ViewOptimizerLib" for configuration "Debug"
set_property(TARGET TMIV::ViewOptimizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::ViewOptimizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/ViewOptimizer/Debug/ViewOptimizerLib.lib"
  )

# Import target "TMIV::PrunerLib" for configuration "Debug"
set_property(TARGET TMIV::PrunerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::PrunerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Pruner/Debug/PrunerLib.lib"
  )

# Import target "TMIV::AggregatorLib" for configuration "Debug"
set_property(TARGET TMIV::AggregatorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::AggregatorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Aggregator/Debug/AggregatorLib.lib"
  )

# Import target "TMIV::PackerLib" for configuration "Debug"
set_property(TARGET TMIV::PackerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::PackerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Packer/Debug/PackerLib.lib"
  )

# Import target "TMIV::GeometryQuantizerLib" for configuration "Debug"
set_property(TARGET TMIV::GeometryQuantizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::GeometryQuantizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/GeometryQuantizer/Debug/GeometryQuantizerLib.lib"
  )

# Import target "TMIV::RendererLib" for configuration "Debug"
set_property(TARGET TMIV::RendererLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::RendererLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Renderer/Debug/RendererLib.lib"
  )

# Import target "TMIV::RendererFrontLib" for configuration "Debug"
set_property(TARGET TMIV::RendererFrontLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::RendererFrontLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Renderer/Debug/RendererFrontLib.lib"
  )

# Import target "TMIV::Renderer" for configuration "Debug"
set_property(TARGET TMIV::Renderer APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::Renderer PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Renderer/Debug/Renderer.exe"
  )

# Import target "TMIV::ViewingSpaceLib" for configuration "Debug"
set_property(TARGET TMIV::ViewingSpaceLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::ViewingSpaceLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/ViewingSpace/Debug/ViewingSpaceLib.lib"
  )

# Import target "TMIV::VideoDecoderLib" for configuration "Debug"
set_property(TARGET TMIV::VideoDecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::VideoDecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/VideoDecoder/Debug/VideoDecoderLib.lib"
  )

# Import target "TMIV::EncoderLib" for configuration "Debug"
set_property(TARGET TMIV::EncoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::EncoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Encoder/Debug/EncoderLib.lib"
  )

# Import target "TMIV::Encoder" for configuration "Debug"
set_property(TARGET TMIV::Encoder APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::Encoder PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Encoder/Debug/Encoder.exe"
  )

# Import target "TMIV::MpiEncoder" for configuration "Debug"
set_property(TARGET TMIV::MpiEncoder APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::MpiEncoder PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Encoder/Debug/MpiEncoder.exe"
  )

# Import target "TMIV::Multiplexer" for configuration "Debug"
set_property(TARGET TMIV::Multiplexer APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::Multiplexer PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Encoder/Debug/Multiplexer.exe"
  )

# Import target "TMIV::DecoderLib" for configuration "Debug"
set_property(TARGET TMIV::DecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::DecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Decoder/Debug/DecoderLib.lib"
  )

# Import target "TMIV::Decoder" for configuration "Debug"
set_property(TARGET TMIV::Decoder APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::Decoder PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Decoder/Debug/Decoder.exe"
  )

# Import target "TMIV::Parser" for configuration "Debug"
set_property(TARGET TMIV::Parser APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::Parser PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Parser/Debug/Parser.exe"
  )

# Import target "TMIV::BitrateReport" for configuration "Debug"
set_property(TARGET TMIV::BitrateReport APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::BitrateReport PROPERTIES
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/Parser/Debug/BitrateReport.exe"
  )

# Import target "TMIV::DepthQualityAssessorLib" for configuration "Debug"
set_property(TARGET TMIV::DepthQualityAssessorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(TMIV::DepthQualityAssessorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Workspace/tmiv_build/source/DepthQualityAssessor/Debug/DepthQualityAssessorLib.lib"
  )

# Import target "TMIV::libmd5" for configuration "Release"
set_property(TARGET TMIV::libmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::libmd5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/Release/libmd5.lib"
  )

# Import target "TMIV::TLibCommon" for configuration "Release"
set_property(TARGET TMIV::TLibCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::TLibCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/Release/TLibCommon.lib"
  )

# Import target "TMIV::TLibDecoder" for configuration "Release"
set_property(TARGET TMIV::TLibDecoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::TLibDecoder PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/Release/TLibDecoder.lib"
  )

# Import target "TMIV::vvencFFapp" for configuration "Release"
set_property(TARGET TMIV::vvencFFapp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::vvencFFapp PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/_deps/vvenc-build/source/App/vvencFFapp/Release/vvencFFapp.exe"
  )

# Import target "TMIV::vvdecapp" for configuration "Release"
set_property(TARGET TMIV::vvdecapp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::vvdecapp PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/_deps/vvdec-build/source/App/vvdecapp/Release/vvdecapp.exe"
  )

# Import target "TMIV::CommonLib" for configuration "Release"
set_property(TARGET TMIV::CommonLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::CommonLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Common/Release/CommonLib.lib"
  )

# Import target "TMIV::fmt" for configuration "Release"
set_property(TARGET TMIV::fmt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::fmt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/_deps/fmt-build/Release/fmt.lib"
  )

# Import target "TMIV::MivBitstreamLib" for configuration "Release"
set_property(TARGET TMIV::MivBitstreamLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::MivBitstreamLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/MivBitstream/Release/MivBitstreamLib.lib"
  )

# Import target "TMIV::IOLib" for configuration "Release"
set_property(TARGET TMIV::IOLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::IOLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/IO/Release/IOLib.lib"
  )

# Import target "TMIV::ViewOptimizerLib" for configuration "Release"
set_property(TARGET TMIV::ViewOptimizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::ViewOptimizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/ViewOptimizer/Release/ViewOptimizerLib.lib"
  )

# Import target "TMIV::PrunerLib" for configuration "Release"
set_property(TARGET TMIV::PrunerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::PrunerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Pruner/Release/PrunerLib.lib"
  )

# Import target "TMIV::AggregatorLib" for configuration "Release"
set_property(TARGET TMIV::AggregatorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::AggregatorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Aggregator/Release/AggregatorLib.lib"
  )

# Import target "TMIV::PackerLib" for configuration "Release"
set_property(TARGET TMIV::PackerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::PackerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Packer/Release/PackerLib.lib"
  )

# Import target "TMIV::GeometryQuantizerLib" for configuration "Release"
set_property(TARGET TMIV::GeometryQuantizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::GeometryQuantizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/GeometryQuantizer/Release/GeometryQuantizerLib.lib"
  )

# Import target "TMIV::RendererLib" for configuration "Release"
set_property(TARGET TMIV::RendererLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::RendererLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Renderer/Release/RendererLib.lib"
  )

# Import target "TMIV::RendererFrontLib" for configuration "Release"
set_property(TARGET TMIV::RendererFrontLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::RendererFrontLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Renderer/Release/RendererFrontLib.lib"
  )

# Import target "TMIV::Renderer" for configuration "Release"
set_property(TARGET TMIV::Renderer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::Renderer PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Renderer/Release/Renderer.exe"
  )

# Import target "TMIV::ViewingSpaceLib" for configuration "Release"
set_property(TARGET TMIV::ViewingSpaceLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::ViewingSpaceLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/ViewingSpace/Release/ViewingSpaceLib.lib"
  )

# Import target "TMIV::VideoDecoderLib" for configuration "Release"
set_property(TARGET TMIV::VideoDecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::VideoDecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/VideoDecoder/Release/VideoDecoderLib.lib"
  )

# Import target "TMIV::EncoderLib" for configuration "Release"
set_property(TARGET TMIV::EncoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::EncoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Encoder/Release/EncoderLib.lib"
  )

# Import target "TMIV::Encoder" for configuration "Release"
set_property(TARGET TMIV::Encoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::Encoder PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Encoder/Release/Encoder.exe"
  )

# Import target "TMIV::MpiEncoder" for configuration "Release"
set_property(TARGET TMIV::MpiEncoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::MpiEncoder PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Encoder/Release/MpiEncoder.exe"
  )

# Import target "TMIV::Multiplexer" for configuration "Release"
set_property(TARGET TMIV::Multiplexer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::Multiplexer PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Encoder/Release/Multiplexer.exe"
  )

# Import target "TMIV::DecoderLib" for configuration "Release"
set_property(TARGET TMIV::DecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::DecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Decoder/Release/DecoderLib.lib"
  )

# Import target "TMIV::Decoder" for configuration "Release"
set_property(TARGET TMIV::Decoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::Decoder PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Decoder/Release/Decoder.exe"
  )

# Import target "TMIV::Parser" for configuration "Release"
set_property(TARGET TMIV::Parser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::Parser PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Parser/Release/Parser.exe"
  )

# Import target "TMIV::BitrateReport" for configuration "Release"
set_property(TARGET TMIV::BitrateReport APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::BitrateReport PROPERTIES
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/Parser/Release/BitrateReport.exe"
  )

# Import target "TMIV::DepthQualityAssessorLib" for configuration "Release"
set_property(TARGET TMIV::DepthQualityAssessorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TMIV::DepthQualityAssessorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Workspace/tmiv_build/source/DepthQualityAssessor/Release/DepthQualityAssessorLib.lib"
  )

# Import target "TMIV::libmd5" for configuration "MinSizeRel"
set_property(TARGET TMIV::libmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::libmd5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/MinSizeRel/libmd5.lib"
  )

# Import target "TMIV::TLibCommon" for configuration "MinSizeRel"
set_property(TARGET TMIV::TLibCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::TLibCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/MinSizeRel/TLibCommon.lib"
  )

# Import target "TMIV::TLibDecoder" for configuration "MinSizeRel"
set_property(TARGET TMIV::TLibDecoder APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::TLibDecoder PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/MinSizeRel/TLibDecoder.lib"
  )

# Import target "TMIV::vvencFFapp" for configuration "MinSizeRel"
set_property(TARGET TMIV::vvencFFapp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::vvencFFapp PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/_deps/vvenc-build/source/App/vvencFFapp/MinSizeRel/vvencFFapp.exe"
  )

# Import target "TMIV::vvdecapp" for configuration "MinSizeRel"
set_property(TARGET TMIV::vvdecapp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::vvdecapp PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/_deps/vvdec-build/source/App/vvdecapp/MinSizeRel/vvdecapp.exe"
  )

# Import target "TMIV::CommonLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::CommonLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::CommonLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Common/MinSizeRel/CommonLib.lib"
  )

# Import target "TMIV::fmt" for configuration "MinSizeRel"
set_property(TARGET TMIV::fmt APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::fmt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/_deps/fmt-build/MinSizeRel/fmt.lib"
  )

# Import target "TMIV::MivBitstreamLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::MivBitstreamLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::MivBitstreamLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/MivBitstream/MinSizeRel/MivBitstreamLib.lib"
  )

# Import target "TMIV::IOLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::IOLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::IOLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/IO/MinSizeRel/IOLib.lib"
  )

# Import target "TMIV::ViewOptimizerLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::ViewOptimizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::ViewOptimizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/ViewOptimizer/MinSizeRel/ViewOptimizerLib.lib"
  )

# Import target "TMIV::PrunerLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::PrunerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::PrunerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Pruner/MinSizeRel/PrunerLib.lib"
  )

# Import target "TMIV::AggregatorLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::AggregatorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::AggregatorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Aggregator/MinSizeRel/AggregatorLib.lib"
  )

# Import target "TMIV::PackerLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::PackerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::PackerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Packer/MinSizeRel/PackerLib.lib"
  )

# Import target "TMIV::GeometryQuantizerLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::GeometryQuantizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::GeometryQuantizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/GeometryQuantizer/MinSizeRel/GeometryQuantizerLib.lib"
  )

# Import target "TMIV::RendererLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::RendererLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::RendererLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Renderer/MinSizeRel/RendererLib.lib"
  )

# Import target "TMIV::RendererFrontLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::RendererFrontLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::RendererFrontLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Renderer/MinSizeRel/RendererFrontLib.lib"
  )

# Import target "TMIV::Renderer" for configuration "MinSizeRel"
set_property(TARGET TMIV::Renderer APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::Renderer PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Renderer/MinSizeRel/Renderer.exe"
  )

# Import target "TMIV::ViewingSpaceLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::ViewingSpaceLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::ViewingSpaceLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/ViewingSpace/MinSizeRel/ViewingSpaceLib.lib"
  )

# Import target "TMIV::VideoDecoderLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::VideoDecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::VideoDecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/VideoDecoder/MinSizeRel/VideoDecoderLib.lib"
  )

# Import target "TMIV::EncoderLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::EncoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::EncoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Encoder/MinSizeRel/EncoderLib.lib"
  )

# Import target "TMIV::Encoder" for configuration "MinSizeRel"
set_property(TARGET TMIV::Encoder APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::Encoder PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Encoder/MinSizeRel/Encoder.exe"
  )

# Import target "TMIV::MpiEncoder" for configuration "MinSizeRel"
set_property(TARGET TMIV::MpiEncoder APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::MpiEncoder PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Encoder/MinSizeRel/MpiEncoder.exe"
  )

# Import target "TMIV::Multiplexer" for configuration "MinSizeRel"
set_property(TARGET TMIV::Multiplexer APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::Multiplexer PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Encoder/MinSizeRel/Multiplexer.exe"
  )

# Import target "TMIV::DecoderLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::DecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::DecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Decoder/MinSizeRel/DecoderLib.lib"
  )

# Import target "TMIV::Decoder" for configuration "MinSizeRel"
set_property(TARGET TMIV::Decoder APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::Decoder PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Decoder/MinSizeRel/Decoder.exe"
  )

# Import target "TMIV::Parser" for configuration "MinSizeRel"
set_property(TARGET TMIV::Parser APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::Parser PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Parser/MinSizeRel/Parser.exe"
  )

# Import target "TMIV::BitrateReport" for configuration "MinSizeRel"
set_property(TARGET TMIV::BitrateReport APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::BitrateReport PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/Parser/MinSizeRel/BitrateReport.exe"
  )

# Import target "TMIV::DepthQualityAssessorLib" for configuration "MinSizeRel"
set_property(TARGET TMIV::DepthQualityAssessorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(TMIV::DepthQualityAssessorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Workspace/tmiv_build/source/DepthQualityAssessor/MinSizeRel/DepthQualityAssessorLib.lib"
  )

# Import target "TMIV::libmd5" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::libmd5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::libmd5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/RelWithDebInfo/libmd5.lib"
  )

# Import target "TMIV::TLibCommon" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::TLibCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::TLibCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/RelWithDebInfo/TLibCommon.lib"
  )

# Import target "TMIV::TLibDecoder" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::TLibDecoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::TLibDecoder PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/RelWithDebInfo/TLibDecoder.lib"
  )

# Import target "TMIV::vvencFFapp" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::vvencFFapp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::vvencFFapp PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/_deps/vvenc-build/source/App/vvencFFapp/RelWithDebInfo/vvencFFapp.exe"
  )

# Import target "TMIV::vvdecapp" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::vvdecapp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::vvdecapp PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/_deps/vvdec-build/source/App/vvdecapp/RelWithDebInfo/vvdecapp.exe"
  )

# Import target "TMIV::CommonLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::CommonLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::CommonLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Common/RelWithDebInfo/CommonLib.lib"
  )

# Import target "TMIV::fmt" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::fmt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::fmt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/_deps/fmt-build/RelWithDebInfo/fmt.lib"
  )

# Import target "TMIV::MivBitstreamLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::MivBitstreamLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::MivBitstreamLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/MivBitstream/RelWithDebInfo/MivBitstreamLib.lib"
  )

# Import target "TMIV::IOLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::IOLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::IOLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/IO/RelWithDebInfo/IOLib.lib"
  )

# Import target "TMIV::ViewOptimizerLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::ViewOptimizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::ViewOptimizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/ViewOptimizer/RelWithDebInfo/ViewOptimizerLib.lib"
  )

# Import target "TMIV::PrunerLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::PrunerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::PrunerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Pruner/RelWithDebInfo/PrunerLib.lib"
  )

# Import target "TMIV::AggregatorLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::AggregatorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::AggregatorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Aggregator/RelWithDebInfo/AggregatorLib.lib"
  )

# Import target "TMIV::PackerLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::PackerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::PackerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Packer/RelWithDebInfo/PackerLib.lib"
  )

# Import target "TMIV::GeometryQuantizerLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::GeometryQuantizerLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::GeometryQuantizerLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/GeometryQuantizer/RelWithDebInfo/GeometryQuantizerLib.lib"
  )

# Import target "TMIV::RendererLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::RendererLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::RendererLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Renderer/RelWithDebInfo/RendererLib.lib"
  )

# Import target "TMIV::RendererFrontLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::RendererFrontLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::RendererFrontLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Renderer/RelWithDebInfo/RendererFrontLib.lib"
  )

# Import target "TMIV::Renderer" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::Renderer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::Renderer PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Renderer/RelWithDebInfo/Renderer.exe"
  )

# Import target "TMIV::ViewingSpaceLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::ViewingSpaceLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::ViewingSpaceLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/ViewingSpace/RelWithDebInfo/ViewingSpaceLib.lib"
  )

# Import target "TMIV::VideoDecoderLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::VideoDecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::VideoDecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/VideoDecoder/RelWithDebInfo/VideoDecoderLib.lib"
  )

# Import target "TMIV::EncoderLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::EncoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::EncoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Encoder/RelWithDebInfo/EncoderLib.lib"
  )

# Import target "TMIV::Encoder" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::Encoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::Encoder PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Encoder/RelWithDebInfo/Encoder.exe"
  )

# Import target "TMIV::MpiEncoder" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::MpiEncoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::MpiEncoder PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Encoder/RelWithDebInfo/MpiEncoder.exe"
  )

# Import target "TMIV::Multiplexer" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::Multiplexer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::Multiplexer PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Encoder/RelWithDebInfo/Multiplexer.exe"
  )

# Import target "TMIV::DecoderLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::DecoderLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::DecoderLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Decoder/RelWithDebInfo/DecoderLib.lib"
  )

# Import target "TMIV::Decoder" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::Decoder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::Decoder PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Decoder/RelWithDebInfo/Decoder.exe"
  )

# Import target "TMIV::Parser" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::Parser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::Parser PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Parser/RelWithDebInfo/Parser.exe"
  )

# Import target "TMIV::BitrateReport" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::BitrateReport APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::BitrateReport PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/Parser/RelWithDebInfo/BitrateReport.exe"
  )

# Import target "TMIV::DepthQualityAssessorLib" for configuration "RelWithDebInfo"
set_property(TARGET TMIV::DepthQualityAssessorLib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(TMIV::DepthQualityAssessorLib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Workspace/tmiv_build/source/DepthQualityAssessor/RelWithDebInfo/DepthQualityAssessorLib.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
